/* Archivo donde estan las acciones de tipo documental de radicacion */
export const AGREGAR_USUARIO_DISPONIBLE = "AGREGAR_USUARIO_DISPONIBLE";
export const BORRAR_USUARIO_DISPONIBLE = "BORRAR_USUARIO_DISPONIBLE";
export const AGREGAR_USUARIO_ORIGINAL = "AGREGAR_USUARIO_ORIGINAL";

/* Archivo donde estan las acciones de tipo tramite */

export const AGREGAR_USUARIO_TIPO_TRAMITE = "AGREGAR_USUARIO_TIPO_TRAMITE";
export const BORRAR_USUARIO_DISPONIBLE_TIPO_TRAMITE =
  "BORRAR_USUARIO_DISPONIBLE_TIPO_TRAMITE";
export const AGREGAR_USUARIO_ORIGINAL_TIPO_TRAMITE =
  "AGREGAR_USUARIO_ORIGINAL_TIPO_TRAMITE";

export const OBTENER_TIPO_TRAMITE_EDITAR = "OBTENER_TIPO_TRAMITE_EDITAR";
export const TIPO_TRAMITE_EDITAR_EXITO = "TIPO_TRAMITE_EDITAR_EXITO";
export const TIPO_TRAMITE_EDITAR_ERROR = "TIPO_TRAMITE_EDITAR_ERROR";
export const COMENZAR_EDICION_TIPO_TRAMITE = "COMENZAR_EDICION_TIPO_TRAMITE";
export const TIPO_TRAMITE_EDITADO_EXITO = "TIPO_TRAMITE_EDITADO_EXITO";
export const TIPO_TRAMITE_EDITADO_ERROR = "TIPO_TRAMITE_EDITADO_ERROR";

/* Fin */
