/* Archivo donde estan las acciones de tipo documental de radicacion */
export const AGREGAR_USUARIO_DISPONIBLE = "AGREGAR_USUARIO_DISPONIBLE";
export const BORRAR_USUARIO_DISPONIBLE = "BORRAR_USUARIO_DISPONIBLE";
export const AGREGAR_USUARIO_ORIGINAL = "AGREGAR_USUARIO_ORIGINAL";

export const OBTENER_TIPO_DOCUMENTAL_RADICACION =
  "OBTENER_TIPO_DOCUMENTAL_RADICACION";
export const TIPO_DOCUMENTAL_RADICACION_EDITAR_EXITO =
  "TIPO_DOCUMENTAL_RADICACION_EDITAR_EXITO";
export const TIPO_DOCUMENTAL_RADICACION_EDITAR_ERROR =
  "TIPO_DOCUMENTAL_RADICACION_EDITAR_ERROR";
export const COMENZAR_EDICION_TIPO_DOCUMENTAL_RADICACION =
  "COMENZAR_EDICION_TIPO_DOCUMENTAL_RADICACION";
export const TIPO_DOCUMENTAL_RADICACION_EDITADO_EXITO =
  "TIPO_DOCUMENTAL_RADICACION_EDITADO_EXITO";
export const TIPO_DOCUMENTAL_RADICACION_EDITADO_ERROR =
  "TIPO_DOCUENTAL_RADICACION_EDITADO_ERROR";

export const AGREGAR_USUARIO_TIPO_DOCUMENTAL_RADICACION_EDITAR =
  " AGREGAR_USUARIO_TIPO_DOCUMENTAL_RADICACION_EDITAR";

export const BORRAR_USUARIO_TIPO_DOCUMENTAL_RADICACION_EDITAR =
  "BORRAR_USUARIO_TIPO_DOCUMENTAL_RADICACION_EDITAR";

export const ASIGNAR_USUARIO_ORIGINAL_TIPO_DOCUMENTAL_RADICACION_EDITAR =
  "ASIGNAR_USUARIO_ORIGINAL_TIPO_DOCUMENTAL_RADICACION_EDITAR";

/* Fin  */

/* Archivo donde estan las acciones de tipo tramite */

export const AGREGAR_USUARIO_TIPO_TRAMITE = "AGREGAR_USUARIO_TIPO_TRAMITE";
export const BORRAR_USUARIO_DISPONIBLE_TIPO_TRAMITE =
  "BORRAR_USUARIO_DISPONIBLE_TIPO_TRAMITE";
export const AGREGAR_USUARIO_ORIGINAL_TIPO_TRAMITE =
  "AGREGAR_USUARIO_ORIGINAL_TIPO_TRAMITE";

export const OBTENER_TIPO_TRAMITE_EDITAR = "OBTENER_TIPO_TRAMITE_EDITAR";
export const TIPO_TRAMITE_EDITAR_EXITO = "TIPO_TRAMITE_EDITAR_EXITO";
export const TIPO_TRAMITE_EDITAR_ERROR = "TIPO_TRAMITE_EDITAR_ERROR";
export const COMENZAR_EDICION_TIPO_TRAMITE = "COMENZAR_EDICION_TIPO_TRAMITE";
export const TIPO_TRAMITE_EDITADO_EXITO = "TIPO_TRAMITE_EDITADO_EXITO";
export const TIPO_TRAMITE_EDITADO_ERROR = "TIPO_TRAMITE_EDITADO_ERROR";

export const AGREGAR_USUARIO_DISPONIBLE_EDITAR =
  "AGREGAR_USUARIO_DISPONIBLE_EDITAR";
export const BORRAR_USUARIO_DISPONIBLE_EDITAR =
  "BORRAR_USUARIO_DISPONIBLE_EDITAR";
export const ASIGNAR_USUARIO_ORIGINAL_EDITAR =
  "ASIGNAR_USUARIO_ORIGINAL_EDITAR";

/* Fin */

/* TYPES DE PLANTILLA */
export const AGREGAR_METADATO_PLANTILLA = "AGREGAR_METADATO_PLANTILLA";
export const ELIMINAR_METADATO_PLANTILLA = "ELIMINAR_METADATO_PLANTILLA";
export const RESET_METADATO_PLANTILLA = "RESET_METADATO_PLANTILLA";
// EDIT METADATA TEMPLATE
export const AGREGAR_METADATO_PLANTILLA_EDITAR =
  "AGREGAR_METADATO_PLANTILLA_EDITAR";
export const ELIMINAR_METADATO_PLANTILLA_EDITAR =
  "ELIMINAR_METADATO_PLANTILLA_EDITAR";
/* FIN */
