/* Archivo donde estan las acciones de tipo documental de radicacion */
export const AGREGAR_USUARIO_DISPONIBLE = "AGREGAR_USUARIO_DISPONIBLE";
export const BORRAR_USUARIO_DISPONIBLE = "BORRAR_USUARIO_DISPONIBLE";
export const AGREGAR_USUARIO_ORIGINAL = "AGREGAR_USUARIO_ORIGINAL";

/* Archivo donde estan las acciones de tipo tramite */
export const AGREGAR_USUARIO_TIPO_TRAMITE = "AGREGAR_USUARIO_TIPO_TRAMITE";
export const BORRAR_USUARIO_DISPONIBLE_TIPO_TRAMITE =
  "BORRAR_USUARIO_DISPONIBLE_TIPO_TRAMITE";
export const AGREGAR_USUARIO_ORIGINAL_TIPO_TRAMITE =
  "AGREGAR_USUARIO_ORIGINAL_TIPO_TRAMITE";

/* Fin */
